packages:
  - apps/*
  - packages/*
  - configs/*
catalog:
  "@tailwindcss/postcss": ^4
  "@types/node": ^25.0.9
  "@types/react": ^19
  "@types/react-dom": ^19
  react: ^19
  react-dom: ^19
  eslint: ^9
  next: ^16
  postcss: ^8.4.49
  tailwindcss: ^4
  typescript: ^5.9.3
  prettier: ^3.8.0
