engineStrict: true
packages:
  - apps/*
  - packages/*
  - configs/*
catalog:
  # Opennext related stuff
  "@opennextjs/cloudflare": 1.17.1
  wrangler: 4.70.0

  # React stuff
  "@types/react": ^19
  "@types/react-dom": ^19
  react: ^19
  react-dom: ^19
  next: ^16

  # Tailwind stuff
  "@tailwindcss/postcss": ^4
  tailwindcss: ^4
  classnames: ^2.5.1
  postcss: ^8

  # Tooling stuff
  "@types/node": ^24
  typescript: ^5.9
  prettier: ^3.8
  eslint: ^9
