import { PropsWithChildren } from 'react';
import cn from 'classnames';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Footer from './_footer';
import Nav from './nav/page';

import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-default',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </head>
      <body className={cn(`${inter.variable} antialiased`)}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
